In [85]:
###################################################
import emcee
import numpy as np
import scipy
from astropy.io import fits
from astropy.table import Table
from astropy.io import fits
import matplotlib.pyplot as plt
from astropy.table import Table
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.cosmology import Planck18 as cosmo
from functools import partial
import time
from astropy.coordinates import SkyCoord
import astropy.units as u
import pyccl as ccl
import clevar
import numpy as np
from astropy.table import Table
import clmm
from clevar.catalog import ClCatalog, MemCatalog
from clevar.match_metrics import recovery
import matplotlib.pyplot as plt
from clevar.match import MembershipMatch
from clevar.match_metrics import distances
from clevar.match_metrics import scaling
from clevar.match import ProximityMatch
from clevar.match_metrics.recovery import ClCatalogFuncs as r_cf
###################################################

# Imports Catalog and creats a table (t_cl) containing Mass ('M'), redshift ('redshift_true') and richness ('NMEM')



t_halo = Table.read("/sps/lsst/groups/clusters/cluster_comparison_project/initial_catalogs/halos/cosmoDC2/halos_nmem_zstar2_10_duplicateHalosRemoved.fits")

t_cl = Table.read("/sps/lsst/groups/clusters/cluster_comparison_project/initial_catalogs/halos/cosmoDC2/halos_nmem_zstar2_10_duplicateHalosRemoved.fits")


t_halo = t_halo[t_halo['m200c'] > 0.0]
t_cl = t_cl[t_cl['m200c'] > 0.0]
Mp, zp = 10**14.3, 0.5



cosmo = ccl.Cosmology(
    Omega_c=0.1109 / 0.71**2,
    Omega_b=0.02258 / 0.71**2,
    h=0.71,
    n_s=0.963,
    sigma8=0.8,
    w0=-1.0,
    wa=0.0,
    transfer_function="boltzmann_camb"
)
display(t_halo)
max_mass = np.max(t_halo['m200c'])
min_mass = np.min(t_halo['m200c'])
# Scientific notation with 2 decimal places
print(f"{max_mass:.2e}, {min_mass:.2e}") 
display(t_cl)
print(np.mean(np.log(t_cl["NMEM"])))

<Table length=164981>
   halo_id         ra_true             dec_true      ... NMEM_z_25.6 NMEM_z_26.1
    int64          float64             float64       ...    int64       int64   
------------- ------------------ ------------------- ... ----------- -----------
   7300151475 50.957678900761394   -41.3448059771583 ...          49          49
  43700151442  49.50377592935664 -40.240490667975706 ...          47          47
  52300151442  51.06907727982047  -39.64607328475867 ...          58          58
  70700151421  50.52541974335929 -39.759854374325954 ...          39          39
  78600151411  50.54038986767568   -39.0704158967892 ...          92          93
  95400151411    50.170338564932  -39.51566808485035 ...         154         154
 130200151411  50.64208660915858  -41.40265859512897 ...         202         202
 191900151411  51.19489753953479  -40.87828426780436 ...          54          54
 253900151411  50.13040773558871  -41.24880382828121 ...          36          36
          ...                ...                 ... ...         ...         ...
7386800146127  74.33997051229849  -39.66180880329787 ...           0           0
7907600146127  74.00046305188938 -38.494450464283716 ...           0           1
 542900146124   74.9787115427494  -39.53938374692757 ...           0           0
 545400146124  75.36350806765532  -38.36460620766874 ...           1           3
1980900146124  74.82861425541878  -39.85589718963985 ...           2           3
3300400146124  74.36169557409839  -38.35375234209698 ...           0           0
3500600146124  74.22276294179544  -38.35001292691405 ...           0           1
4598700146124  74.04986283325118  -39.36388804633259 ...           0           0
1486000146121  74.13452829620286 -38.530131826966084 ...           1           3
4773800146121  74.31543023533824  -38.76409304018537 ...           1           1

1.88e+15, 2.61e+12


<Table length=164981>
   halo_id         ra_true             dec_true      ... NMEM_z_25.6 NMEM_z_26.1
    int64          float64             float64       ...    int64       int64   
------------- ------------------ ------------------- ... ----------- -----------
   7300151475 50.957678900761394   -41.3448059771583 ...          49          49
  43700151442  49.50377592935664 -40.240490667975706 ...          47          47
  52300151442  51.06907727982047  -39.64607328475867 ...          58          58
  70700151421  50.52541974335929 -39.759854374325954 ...          39          39
  78600151411  50.54038986767568   -39.0704158967892 ...          92          93
  95400151411    50.170338564932  -39.51566808485035 ...         154         154
 130200151411  50.64208660915858  -41.40265859512897 ...         202         202
 191900151411  51.19489753953479  -40.87828426780436 ...          54          54
 253900151411  50.13040773558871  -41.24880382828121 ...          36          36
          ...                ...                 ... ...         ...         ...
7386800146127  74.33997051229849  -39.66180880329787 ...           0           0
7907600146127  74.00046305188938 -38.494450464283716 ...           0           1
 542900146124   74.9787115427494  -39.53938374692757 ...           0           0
 545400146124  75.36350806765532  -38.36460620766874 ...           1           3
1980900146124  74.82861425541878  -39.85589718963985 ...           2           3
3300400146124  74.36169557409839  -38.35375234209698 ...           0           0
3500600146124  74.22276294179544  -38.35001292691405 ...           0           1
4598700146124  74.04986283325118  -39.36388804633259 ...           0           0
1486000146121  74.13452829620286 -38.530131826966084 ...           1           3
4773800146121  74.31543023533824  -38.76409304018537 ...           1           1

3.4934730051232936


In [71]:
## Mass-Richness

In [80]:
def prior(params):
    if len(params) == 6:
        A, B, C, D, E, F = params
        if -2<C<2 and -2<E<2 and -2<F<2 and A > 0 and B > 0 and D > 0:
            return True
        else:
            return False
    else:
        A, B, D, E = params
        if -2<E<2 and A > 0 and B > 0 and D > 0:
            return True
        else:
            return False
def _ln_L(params, X, a, b, use_correction):
    # 1. Prior Check
    if not prior(params):
        return -np.inf
    
    # 2. Extract Data & Params
    pop, M, z = np.log(X["NMEM"]), X["m200c"], X["redshift_true"]
    
    if len(params) == 6:
        A, B, C, D, E, F = params
        mean_alpha = A + B*np.log(M/Mp) + C*np.log((1+z)/(1+zp))
        sigma = D + E*np.log(M/Mp) + F*np.log((1+z)/(1+zp))
    else:
        A, B, D, E = params
        mean_alpha = A + B*np.log(M/Mp)
        sigma = D + E*np.log(M/Mp)
    
    # 3. Physicality Check (Sigma must be positive for all points)
    if np.any(sigma <= 0):
        return -np.inf
    
    # 4. Standard Log-likelihood calculation
    # Using np.sum for speed and stability
    term1 = -0.5 * np.log(2 * np.pi * sigma**2)
    term2 = -0.5 * ((pop - mean_alpha) / sigma)**2
    ln_L = np.sum(term1 + term2)
    
    # 5. Optional Truncation Correction (Corrected logic)
    if use_correction:
        # P(a < NMEM < b) = 0.5 * [erf((log(b)-mu)/(sig*sqrt2)) - erf((log(a)-mu)/(sig*sqrt2))]
        inv_sig_root2 = 1.0 / (sigma * np.sqrt(2))
        def erf_func(val):
            return scipy.special.erf((np.log(val) - mean_alpha) * inv_sig_root2)
        
        prob_in_bin = 0.5 * (erf_func(b) - erf_func(a))
        # Add the log of the normalization to the total likelihood
        ln_L -= np.sum(np.log(np.clip(prob_in_bin, 1e-10, None)))
        
    return ln_L

def MCMC(richesse_bin, redshift_bin, itt, redshift_params=True, correction=True):
    a, b = richesse_bin
    c, d = redshift_bin
    
    # Selection
    mask = (t_cl["NMEM"] > a) & (t_cl["NMEM"] < b) & \
           (t_cl["redshift_true"] > c) & (t_cl["redshift_true"] < d)
    X = t_cl[mask]
    display(X)
    if len(X) < 10: # Safety check for empty bins
        print(f"Warning: Bin {richesse_bin}, {redshift_bin} has only {len(X)} clusters.")
        return {'mean': np.zeros(6 if redshift_params else 4), 'std': np.zeros(6 if redshift_params else 4)}

    ndim = 6 if redshift_params else 4
    nwalkers = 48 # Use a multiple of 2 or 4 for better threading
    
    # Better initialization
    if redshift_params:
        guess = np.array([3.2, 0.8, 0.1, 0.5, 0.01, 0.01])
    else:
        guess = np.array([3.2, 0.8, 0.5, 0.01])
        
    p0 = [guess + 1e-4 * np.random.randn(ndim) for i in range(nwalkers)]
    
    sampler = emcee.EnsembleSampler(nwalkers, ndim, _ln_L, args=[X, a, b, correction])
    sampler.run_mcmc(p0, itt, progress=True)
    
    # Correct result extraction (Flattening)
    burn_in = int(itt * 0.3)
    unflat_samples = sampler.get_chain(discard=burn_in, flat=False)
    flat_samples = sampler.get_chain(discard=burn_in, flat=True)    
    return {
        'chains': unflat_samples,
        'mean': np.mean(flat_samples, axis=0),
        'std': np.std(flat_samples, axis=0)
    }

In [81]:
### Unbinned relation

In [82]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

# ------------------------------------------------------------------------------
# Assuming you run MCMC once for all clusters (global), returns 6 parameters
# ------------------------------------------------------------------------------

# Run your MCMC once
res = MCMC(richesse_bin=(40,200), 
          redshift_bin=(0.2,1.0), 
          itt=2000, redshift_params=True, correction=False)

# Extract chains and statistics
chains = res['chains']  # shape: (nsteps, nwalkers, 6) or similar
means = res['mean']     # length 6
stds  = res['std']      # length 6

# Print best-fit values
param_names = ['A','B','C','D','E','F']
for i, name in enumerate(param_names):
    print(f"{name}: mean={means[i]:.4f}, std={stds[i]:.4f}")

# ------------------------------------------------------------------------------
# Plot chains to check convergence
# ------------------------------------------------------------------------------
n_params = 6
nsteps, nwalkers = chains.shape[0], chains.shape[1]

fig, axes = plt.subplots(n_params, 1, figsize=(12, 2*n_params), sharex=True)
for i in range(n_params):
    ax = axes[i]
    for w in range(nwalkers):
        ax.plot(chains[:, w, i], alpha=0.5)
    # Show mean and median lines
    mean_i = np.mean(chains[:, :, i])
    median_i = np.median(chains[:, :, i])
    ax.axhline(mean_i, color='red', linestyle='--', label='Mean')
    ax.axhline(median_i, color='green', linestyle='-.', label='Median')
    ax.set_ylabel(param_names[i])
    ax.legend()
axes[-1].set_xlabel('MCMC step')
plt.tight_layout()
plt.show()


<Table length=17358>
   halo_id         ra_true             dec_true      ... NMEM_z_25.6 NMEM_z_26.1
    int64          float64             float64       ...    int64       int64   
------------- ------------------ ------------------- ... ----------- -----------
  78600151411  50.54038986767568   -39.0704158967892 ...          92          93
  95400151411    50.170338564932  -39.51566808485035 ...         154         154
  95200151401  51.51918683257815  -40.75236849405238 ...          46          48
 138000151401  50.34738589649655  -40.83606966007568 ...          64          66
 130400151392  50.71714143417555 -41.528716082372455 ...         109         112
 349000151382  49.99763790043953  -40.75255486327657 ...          81          81
 430200151382  50.68338173774685   -38.9452777296178 ...          41          42
  48900151373  51.32245069550807  -40.14787708508766 ...         113         115
 397900151373 50.086766251266965 -40.243365459795626 ...         170         174
          ...                ...                 ... ...         ...         ...
2083900146247  75.54771970690929  -38.71060413892894 ...          50          63
2212500146247  74.16740684477215 -38.510364322585616 ...          36          41
2421000146247  74.85715833179034  -37.61143654202414 ...          27          32
2487700146247  75.14973404072904  -38.00063666257421 ...          47          52
2501100146247  73.99032231071858  -38.75709407267209 ...          50          59
2555400146247  74.47612208970673  -37.30089256807614 ...          35          37
2824800146247  74.54120322377513  -38.23737478533408 ...          29          35
2847100146247  73.69440658209149  -39.27660612650885 ...          29          35
3204400146247  75.36767753832136  -38.94821359713737 ...          35          42
3643000146247  75.25291252681667  -38.35142028664353 ...          34          43

100%|██████████| 2000/2000 [01:04<00:00, 31.14it/s]


A: mean=4.8092, std=0.0057
B: mean=0.5968, std=0.0052
C: mean=0.2464, std=0.0157
D: mean=0.2630, std=0.0037
E: mean=0.0040, std=0.0032
F: mean=-0.0555, std=0.0110


In [26]:
from getdist import plots, MCSamples
import numpy as np

# 1. Create the MCSamples object (keep your existing setup)
# samples = MCSamples(samples=flat_samples, names=param_names, labels=param_labels)

# 2. Get Marginalized Statistics (Mean and 1-sigma limits)
stats = samples.getMargeStats()

print(f"{'Parameter':<10} | {'Mean':<10} | {'1-sigma Lower':<15} | {'1-sigma Upper':<15}")
print("-" * 70)

for i, name in enumerate(param_names):
    par = stats.parWithName(name)
    # par.mean is the average; par.limits[0] is the 68% confidence interval
    print(f"{name:<10} | {par.mean:10.4f} | {par.limits[0].lower:15.4f} | {par.limits[0].upper:15.4f}")

# 3. Get the "Best Fit" (Peak of the 1D marginalized distribution)
# In GetDist, we use the sample's internal density estimator for this.
print("\nMarginalized Peak (Mode) / 'Best Fit':")
for i, name in enumerate(param_names):
    # This finds the peak of the KDE for each 1D parameter
    best_val = samples.getInlineLatex(name, limit=1)
    print(f"{name}: {best_val}")

# 4. Generate the Triangle Plot
# This is the most robust way to visualize the "Best Fit"
g = plots.get_subplot_plotter()
g.triangle_plot(samples, 
                filled=True, 
                title_limit=1) # title_limit=1 prints the Mean +/- 1-sigma on top

# If you want to mark the Mean on the plots as a reference:
# markers = {n: samples.getMargeStats().parWithName(n).mean for n in param_names}
# g.triangle_plot(samples, markers=markers, filled=True)

plt.show()

Parameter  | Mean       | 1-sigma Lower   | 1-sigma Upper  
----------------------------------------------------------------------
A          |     4.5215 |          4.5166 |          4.5265
B          |     0.5333 |          0.5304 |          0.5363
C          |     0.1571 |          0.1453 |          0.1689
D          |     0.2649 |          0.2615 |          0.2683
E          |     0.0048 |          0.0028 |          0.0068
F          |    -0.0440 |         -0.0521 |         -0.0359

Marginalized Peak (Mode) / 'Best Fit':
A: A_{\mu} = 4.5215\pm 0.0049
B: B_{\mu} = 0.5333\pm 0.0030
C: C_{\mu} = 0.157\pm 0.012
D: D_{\sigma} = 0.2649\pm 0.0034
E: E_{\sigma} = 0.0048\pm 0.0020
F: F_{\sigma} = -0.0440\pm 0.0081


In [27]:
## Save to sacc

In [34]:
import math
import itertools

import numpy as np

from numcosmo_py import Nc
from numcosmo_py import Ncm

from astropy.table import Table

from astropy.io import fits
from scipy import stats
from typing import Any
import sacc

data_table = t_cl
data_table = data_table[data_table['redshift_true'] >= 0.2]
data_table = data_table[data_table['redshift_true'] <= 0.8]
print(data_table.colnames, len(data_table))

area = 439.78986

cluster_z = data_table["redshift_true"]
cluster_richness = np.log10(data_table["NMEM"])

N_richness = 5  # number of richness bins
N_z = 4  # number of redshift bins

cluster_counts, z_edges, richness_edges, _ = stats.binned_statistic_2d(
    cluster_z, cluster_richness, None, "count", bins=[N_z, N_richness]
)
print(cluster_counts)
print(np.sum(cluster_counts))
covariance = np.diag(cluster_counts.flatten())
print(np.mean(cluster_z), np.min(cluster_z))
s_count = sacc.Sacc()
bin_z_labels = []
bin_richness_labels = []

survey_name = "cosmodc2_wazp_halos"
s_count.add_tracer("survey", survey_name, area)

for i, z_bin in enumerate(zip(z_edges[:-1], z_edges[1:])):
    lower, upper = z_bin
    bin_z_label = f"bin_z_{i}"
    s_count.add_tracer("bin_z", bin_z_label, lower, upper)
    bin_z_labels.append(bin_z_label)

for i, richness_bin in enumerate(zip(richness_edges[:-1], richness_edges[1:])):
    lower, upper = richness_bin
    bin_richness_label = f"rich_{i}"
    s_count.add_tracer("bin_richness", bin_richness_label, lower, upper)
    bin_richness_labels.append(bin_richness_label)

#  pylint: disable-next=no-member
cluster_count = sacc.standard_types.cluster_counts

counts_and_edges = zip(
    cluster_counts.flatten(), itertools.product(bin_z_labels, bin_richness_labels)
)


for counts, (bin_z_label, bin_richness_label) in counts_and_edges:
    s_count.add_data_point(
        cluster_count, (survey_name, bin_richness_label, bin_z_label), int(counts)
    )
s_count.add_covariance(covariance)
s_count.to_canonical_order()
s_count.save_fits("./outputs_mor/clusters_sacc_file_cov.sacc", overwrite=True)
s_count.save_fits("cluster_sacc_catalog.sacc", overwrite=True)


['halo_id', 'ra_true', 'dec_true', 'redshift_true', 'halo_mass', 'NMEM', 'files', 'baseDC2/target_halo_fof_halo_id', 'm200c', 'r200c', 'skysim_mtID_m200c', 'skysim_mtID_r200c', 'skysim_mtID_halo_id', 'skysim_mtID_dist_deg', 'skysim_mtID_pixel', 'skysim_mtID_ind', 'skysim_mtID_inds', 'skysim_mtMZ_m200c', 'skysim_mtMZ_r200c', 'skysim_mtMZ_halo_id', 'skysim_mtMZ_dist_deg', 'skysim_mtMZ_pixel', 'skysim_mtMZ_ind', 'skysim_mtMZ_halo_mass', 'skysim_mtMZ_redshift_true', 'NMEM_r_star2', 'NMEM_i_star2', 'NMEM_z_star2', 'NMEM_y_star2', 'NMEM_r_star1.5', 'NMEM_i_star1.5', 'NMEM_z_star1.5', 'NMEM_y_star1.5', 'NMEM_z_25.6', 'NMEM_z_26.1'] 22392
[[ 378. 1209.  591.  120.    8.]
 [ 667. 2587. 1026.  195.   14.]
 [ 995. 3809. 1358.  223.   11.]
 [1925. 5391. 1635.  236.   14.]]
22392.0
0.5810012975018891 0.20034563541412354


In [54]:
import numpy as np
import pandas as pd
import GCRCatalogs
from crow import mass_proxy
from crow import ClusterAbundance
import pyarrow.parquet as pq
import pyarrow as pa
import matplotlib.pyplot as plt
from astropy.table import Table
# Imports
import time
import numpy as np
import matplotlib.pyplot as plt
import pyccl as ccl
from scipy.interpolate import interp1d

from crow import ClusterShearProfile
from crow import ClusterAbundance
from crow.recipes.binned_exact import ExactBinnedClusterRecipe
from crow.recipes.binned_grid import GridBinnedClusterRecipe
from crow import completeness_models, mass_proxy, purity_models, kernel
from crow.properties import ClusterProperty

# ---- Core cosmology and HMF (same numbers as your example) ----
hmf = ccl.halos.MassFuncDespali16(mass_def="200c")

cosmo = ccl.Cosmology(
    Omega_c=0.1109 / 0.71**2,
    Omega_b=0.02258 / 0.71**2,
    h=0.71,
    n_s=0.963,
    sigma8=0.8,
    w0=-1.0,
    wa=0.0,
    transfer_function="boltzmann_camb"
)

mass_richness
# ---- Common grid / binning parameters for later cells ----
mass_grid_size = 80
redshift_grid_size = 40
proxy_grid_size = 40
sky_area = 440
mass_interval = (12.5, 15.27)


cl_abundandce = ClusterAbundance(cosmo, hmf)
m_pivot = 14.3
z_pivot = 0.5
z_bins = [(z_edges[i], z_edges[i+1]) for i in range(len(z_edges) -1)]
proxy_bins = [(richness_edges[i], richness_edges[i+1]) for i in range(len(richness_edges) - 1)]
redshift_distribution = kernel.SpectroscopicRedshift()
mass_richness = mass_proxy.MurataUnbinned(m_pivot, z_pivot)

mass_richness.parameters["mu0"] = 4.5215
mass_richness.parameters["mu1"] = 0.5333
mass_richness.parameters["mu2"] = 0.1571

mass_richness.parameters["sigma0"] = 0.2649
mass_richness.parameters["sigma1"] = 0.0048
mass_richness.parameters["sigma2"] = -0.0440

print(z_edges, richness_edges)
# ---- Common grid / binning parameters for later cells ----
mass_grid_size = 80
redshift_grid_size = 40
proxy_grid_size = 40
sky_area = 440
mass_interval = (12.5, 15.0)


cl_abundandce = ClusterAbundance(cosmo, hmf)

recipe_grid_nocomp = GridBinnedClusterRecipe(
    mass_interval=mass_interval,
    cluster_theory=cl_abundandce,
    redshift_distribution=redshift_distribution,
    mass_distribution=mass_richness,
    proxy_grid_size=proxy_grid_size,
    redshift_grid_size=redshift_grid_size,
    mass_grid_size=mass_grid_size,
)
recipe_grid_nocomp.setup()


exact_t0 = time.time()
grid_nocomp_vals  = np.zeros((len(z_edges) -1,len(richness_edges) - 1))

for i, zb in enumerate(z_bins):
    for j, pb in enumerate(proxy_bins):
        grid_nocomp_vals[i,j]  = recipe_grid_nocomp.evaluate_theory_prediction_counts(np.array(zb), np.array(pb), sky_area)

[0.20034564 0.3502579  0.50017017 0.65008244 0.79999471] [1.04139269 1.43457834 1.82776399 2.22094965 2.6141353  3.00732095]


In [55]:
print(grid_nocomp_vals)

[[4.41108707e+03 4.03272047e+02 1.08519734e+01 5.86093946e-03
  9.37653871e-10]
 [8.46322760e+03 6.90913386e+02 1.56067558e+01 7.17491317e-03
  8.19714413e-10]
 [1.21445153e+04 8.71078114e+02 1.60007985e+01 6.09141438e-03
  5.00027293e-10]
 [1.47419217e+04 9.16063630e+02 1.33035670e+01 4.07044959e-03
  2.41516731e-10]]
