In [15]:
###################################################
import emcee
import numpy as np
import scipy
from astropy.io import fits
from astropy.table import Table
from astropy.io import fits
import matplotlib.pyplot as plt
from astropy.table import Table
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.cosmology import Planck18 as cosmo
from functools import partial
import time
from astropy.coordinates import SkyCoord
import astropy.units as u
import pyccl as ccl
import clevar
import numpy as np
from astropy.table import Table
import clmm
from clevar.catalog import ClCatalog, MemCatalog
from clevar.match_metrics import recovery
import matplotlib.pyplot as plt
from clevar.match import MembershipMatch
from clevar.match_metrics import distances
from clevar.match_metrics import scaling
from clevar.match import ProximityMatch
from clevar.match_metrics.recovery import ClCatalogFuncs as r_cf
###################################################

# Imports Catalog and creats a table (t_cl) containing Mass ('M'), redshift ('redshift_true') and richness ('NMEM')


t_halo = Table.read("/sps/lsst/groups/clusters/cl_pipeline_project/pywazp_gaussian_catalogs/matched_halo_cluster_catalog.fits")
t_cl = Table.read("/sps/lsst/groups/clusters/cl_pipeline_project/pywazp_gaussian_catalogs/matched_halo_cluster_catalog.fits")

t_halo = t_halo[t_halo['m200c'] > 10**13.0]
t_cl = t_cl[t_cl['m200c'] > 10**13.0]
#t_cl = t_cl[t_cl['snr'] > 10.0]
Mp, zp = 10**14.3, 0.5



cosmo = ccl.Cosmology(
    Omega_c=0.1109 / 0.71**2,
    Omega_b=0.02258 / 0.71**2,
    h=0.71,
    n_s=0.963,
    sigma8=0.8,
    w0=-1.0,
    wa=0.0,
    transfer_function="boltzmann_camb"
)
display(t_halo)
max_mass = np.max(t_halo['m200c'])
min_mass = np.min(t_halo['m200c'])
# Scientific notation with 2 decimal places
print(f"{max_mass:.2e}, {min_mass:.2e}") 
display(t_cl)


<Table length=86636>
        ra                 dec         ...       dec_true      NMEM_true
     float64             float64       ...       float64         int64  
------------------ ------------------- ... ------------------- ---------
 50.93591472649795  -41.34538693217072 ...   -41.3448059771583        13
 49.49706323474621 -40.242985768257384 ... -40.240490667975706        12
 51.11978122453714 -39.620245431872505 ...  -39.64607328475867        16
50.530714428897404  -39.75747779430141 ... -39.759854374325954        16
50.538536858117084 -39.068128185514055 ...   -39.0704158967892        31
 50.17085292813019  -39.51418400574235 ...  -39.51566808485035        59
 50.63606969044204  -41.40247981147909 ...  -41.40265859512897        84
51.192978766528704   -40.8759233021217 ...  -40.87828426780436        24
 50.13097168819828  -41.25581068917369 ...  -41.24880382828121        13
               ...                 ... ...                 ...       ...
 74.35130415885358  -39.86827760660723 ... -39.869545522562106        11
 74.91954909544435  -39.07531873716236 ... -39.073899208752124        13
  74.4364280426933 -39.375735948732626 ... -39.373856204898146        13
 75.16969962277358 -38.954109956405865 ...  -38.95628318823907        18
 74.41464749308474   -38.0797365156017 ... -38.079658053908275        12
 75.01165986441778 -39.566615303776835 ...    -39.566758767609        13
 73.86879598098858  -38.60901614376313 ...   -38.6070532884487        51
 74.67533640282065  -39.41551706614469 ... -39.415367586925015        10
 74.63161709055147  -38.24249921007095 ...  -38.24392143574187        14
 74.34004611459136  -39.14766138904054 ...  -39.14980246610139        16

1.88e+15, 1.00e+13


<Table length=86636>
        ra                 dec         ...       dec_true      NMEM_true
     float64             float64       ...       float64         int64  
------------------ ------------------- ... ------------------- ---------
 50.93591472649795  -41.34538693217072 ...   -41.3448059771583        13
 49.49706323474621 -40.242985768257384 ... -40.240490667975706        12
 51.11978122453714 -39.620245431872505 ...  -39.64607328475867        16
50.530714428897404  -39.75747779430141 ... -39.759854374325954        16
50.538536858117084 -39.068128185514055 ...   -39.0704158967892        31
 50.17085292813019  -39.51418400574235 ...  -39.51566808485035        59
 50.63606969044204  -41.40247981147909 ...  -41.40265859512897        84
51.192978766528704   -40.8759233021217 ...  -40.87828426780436        24
 50.13097168819828  -41.25581068917369 ...  -41.24880382828121        13
               ...                 ... ...                 ...       ...
 74.35130415885358  -39.86827760660723 ... -39.869545522562106        11
 74.91954909544435  -39.07531873716236 ... -39.073899208752124        13
  74.4364280426933 -39.375735948732626 ... -39.373856204898146        13
 75.16969962277358 -38.954109956405865 ...  -38.95628318823907        18
 74.41464749308474   -38.0797365156017 ... -38.079658053908275        12
 75.01165986441778 -39.566615303776835 ...    -39.566758767609        13
 73.86879598098858  -38.60901614376313 ...   -38.6070532884487        51
 74.67533640282065  -39.41551706614469 ... -39.415367586925015        10
 74.63161709055147  -38.24249921007095 ...  -38.24392143574187        14
 74.34004611459136  -39.14766138904054 ...  -39.14980246610139        16

In [16]:
## Mass-Richness

In [17]:
def prior(params):
    if len(params) == 6:
        A, B, C, D, E, F = params
        if -2<C<2 and -2<E<2 and -2<F<2 and A > 0 and B > 0 and D > 0:
            return True
        else:
            return False
    else:
        A, B, D, E = params
        if -2<E<2 and A > 0 and B > 0 and D > 0:
            return True
        else:
            return False
def _ln_L(params, X, a, b, use_correction):
    # 1. Prior Check
    if not prior(params):
        return -np.inf
    
    # 2. Extract Data & Params
    pop, M, z = np.log(X["n200"]), X["m200c"], X["z_h"]
    
    if len(params) == 6:
        A, B, C, D, E, F = params
        mean_alpha = A + B*np.log(M/Mp) + C*np.log((1+z)/(1+zp))
        sigma = D + E*np.log(M/Mp) + F*np.log((1+z)/(1+zp))
    else:
        A, B, D, E = params
        mean_alpha = A + B*np.log(M/Mp)
        sigma = D + E*np.log(M/Mp)
    
    # 3. Physicality Check (Sigma must be positive for all points)
    if np.any(sigma <= 0):
        return -np.inf
    
    # 4. Standard Log-likelihood calculation
    # Using np.sum for speed and stability
    term1 = -0.5 * np.log(2 * np.pi * sigma**2)
    term2 = -0.5 * ((pop - mean_alpha) / sigma)**2
    ln_L = np.sum(term1 + term2)
    
    # 5. Optional Truncation Correction (Corrected logic)
    if use_correction:
        # P(a < NMEM < b) = 0.5 * [erf((log(b)-mu)/(sig*sqrt2)) - erf((log(a)-mu)/(sig*sqrt2))]
        inv_sig_root2 = 1.0 / (sigma * np.sqrt(2))
        def erf_func(val):
            return scipy.special.erf((np.log(val) - mean_alpha) * inv_sig_root2)
        
        prob_in_bin = 0.5 * (erf_func(b) - erf_func(a))
        # Add the log of the normalization to the total likelihood
        ln_L -= np.sum(np.log(np.clip(prob_in_bin, 1e-10, None)))
        
    return ln_L

def MCMC(richesse_bin, redshift_bin, itt, redshift_params=True, correction=True):
    a, b = richesse_bin
    c, d = redshift_bin
    
    # Selection
    mask = (t_cl["n200"] > a) & (t_cl["n200"] < b) & \
           (t_cl["zp"] > c) & (t_cl["z_h"] < d) 
            
    X = t_cl[mask]
    display(X)
    if len(X) < 10: # Safety check for empty bins
        print(f"Warning: Bin {richesse_bin}, {redshift_bin} has only {len(X)} clusters.")
        return {'mean': np.zeros(6 if redshift_params else 4), 'std': np.zeros(6 if redshift_params else 4)}

    ndim = 6 if redshift_params else 4
    nwalkers = 48 # Use a multiple of 2 or 4 for better threading
    
    # Better initialization
    if redshift_params:
        guess = np.array([3.2, 0.8, 0.1, 0.5, 0.01, 0.01])
    else:
        guess = np.array([3.2, 0.8, 0.5, 0.01])
        
    p0 = [guess + 1e-4 * np.random.randn(ndim) for i in range(nwalkers)]
    
    sampler = emcee.EnsembleSampler(nwalkers, ndim, _ln_L, args=[X, a, b, correction])
    sampler.run_mcmc(p0, itt, progress=True)
    
    # Correct result extraction (Flattening)
    burn_in = int(itt * 0.3)
    unflat_samples = sampler.get_chain(discard=burn_in, flat=False)
    flat_samples = sampler.get_chain(discard=burn_in, flat=True)    
    return {
        'chains': unflat_samples,
        'mean': np.mean(flat_samples, axis=0),
        'std': np.std(flat_samples, axis=0)
    }

In [18]:
### Unbinned relation

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

# ------------------------------------------------------------------------------
# Assuming you run MCMC once for all clusters (global), returns 6 parameters
# ------------------------------------------------------------------------------

# Run your MCMC once
res = MCMC(richesse_bin=(20,100), 
          redshift_bin=(0.2,.8), 
          itt=4000, redshift_params=True, correction=False)

# Extract chains and statistics
chains = res['chains']  # shape: (nsteps, nwalkers, 6) or similar
means = res['mean']     # length 6
stds  = res['std']      # length 6

# Print best-fit values
param_names = ['A','B','C','D','E','F']
for i, name in enumerate(param_names):
    print(f"{name}: mean={means[i]:.4f}, std={stds[i]:.4f}")

# ------------------------------------------------------------------------------
# Plot chains to check convergence
# ------------------------------------------------------------------------------
n_params = 6
nsteps, nwalkers = chains.shape[0], chains.shape[1]

fig, axes = plt.subplots(n_params, 1, figsize=(12, 2*n_params), sharex=True)
for i in range(n_params):
    ax = axes[i]
    for w in range(nwalkers):
        ax.plot(chains[:, w, i], alpha=0.5)
    # Show mean and median lines
    mean_i = np.mean(chains[:, :, i])
    median_i = np.median(chains[:, :, i])
    ax.axhline(mean_i, color='red', linestyle='--', label='Mean')
    ax.axhline(median_i, color='green', linestyle='-.', label='Median')
    ax.set_ylabel(param_names[i])
    ax.legend()
axes[-1].set_xlabel('MCMC step')
plt.tight_layout()
plt.show()


<Table length=5018>
        ra                 dec         ...       dec_true      NMEM_true
     float64             float64       ...       float64         int64  
------------------ ------------------- ... ------------------- ---------
50.538536858117084 -39.068128185514055 ...   -39.0704158967892        31
 50.17085292813019  -39.51418400574235 ...  -39.51566808485035        59
 49.97226138364417  -40.73031619826872 ...  -40.75255486327657        24
51.325479965042895  -40.14407238374118 ...  -40.14787708508766        36
 50.08448729912273  -40.24338303417428 ... -40.243365459795626        40
 50.64919312233315 -41.148156431317936 ...  -41.14788942941232        31
 51.53591402608318 -40.105900748250654 ...  -40.10519064315011        32
 50.74465568477031  -38.94572601222099 ...   -38.9417925943923        31
 50.41915077056092  -39.58962833579833 ... -39.590857084167055        39
               ...                 ... ...                 ...       ...
 74.36966231804276  -38.78340607972346 ... -38.783800558202756        18
 74.24859902144323  -39.31698695084361 ...  -39.31730036835148        20
  74.1052360159937  -39.28453900966945 ...  -39.28325619333103        28
 74.52753595256411 -38.786152196770715 ...  -38.78602092611612        28
 74.33651249116404  -38.19273450785209 ...  -38.19465114137441        27
 74.00594116141309  -38.73335077901277 ...  -38.73373537094034        12
 74.49438289674796  -38.71263307852296 ...  -38.71242560753166        77
 73.77498242493371 -38.782292965930246 ...  -38.78875868537267        69
 73.66039333482222  -38.51217236826428 ...  -38.51229291483733        34
  73.3307665379308  -38.49235068633392 ...  -38.49281003778947        50

100%|██████████| 4000/4000 [00:52<00:00, 75.97it/s]


A: mean=3.6238, std=0.0076
B: mean=0.2480, std=0.0070
C: mean=0.0351, std=0.0418
D: mean=0.3591, std=0.0049
E: mean=0.0696, std=0.0040
F: mean=-0.0226, std=0.0284


In [20]:
## Save to sacc

In [21]:
import math
import itertools

import numpy as np

from numcosmo_py import Nc
from numcosmo_py import Ncm

from astropy.table import Table

from astropy.io import fits
from scipy import stats
from typing import Any
import sacc

data_table = t_cl
data_table = data_table[data_table['z_h'] >= 0.2]
data_table = data_table[data_table['z_h'] <= 0.8]
print(data_table.colnames, len(data_table))

area = 439.78986

cluster_z = data_table["z_h"]
cluster_richness = np.log10(data_table["n200"])

N_richness = 5  # number of richness bins
N_z = 4  # number of redshift bins

cluster_counts, z_edges, richness_edges, _ = stats.binned_statistic_2d(
    cluster_z, cluster_richness, None, "count", bins=[N_z, N_richness]
)
print(cluster_counts)
print(np.sum(cluster_counts))
covariance = np.diag(cluster_counts.flatten())
print(np.mean(cluster_z), np.min(cluster_z))
s_count = sacc.Sacc()
bin_z_labels = []
bin_richness_labels = []

survey_name = "cosmodc2_wazp_halos"
s_count.add_tracer("survey", survey_name, area)

for i, z_bin in enumerate(zip(z_edges[:-1], z_edges[1:])):
    lower, upper = z_bin
    bin_z_label = f"bin_z_{i}"
    s_count.add_tracer("bin_z", bin_z_label, lower, upper)
    bin_z_labels.append(bin_z_label)

for i, richness_bin in enumerate(zip(richness_edges[:-1], richness_edges[1:])):
    lower, upper = richness_bin
    bin_richness_label = f"rich_{i}"
    s_count.add_tracer("bin_richness", bin_richness_label, lower, upper)
    bin_richness_labels.append(bin_richness_label)

#  pylint: disable-next=no-member
cluster_count = sacc.standard_types.cluster_counts

counts_and_edges = zip(
    cluster_counts.flatten(), itertools.product(bin_z_labels, bin_richness_labels)
)


for counts, (bin_z_label, bin_richness_label) in counts_and_edges:
    s_count.add_data_point(
        cluster_count, (survey_name, bin_richness_label, bin_z_label), int(counts)
    )
s_count.add_covariance(covariance)
s_count.to_canonical_order()
s_count.save_fits("./outputs_mor/clusters_sacc_file_cov.sacc", overwrite=True)
s_count.save_fits("cluster_sacc_catalog.sacc", overwrite=True)


['ra', 'dec', 'zp', 'n200', 'r200_mpc', 'id', 'snr', 'mt_self', 'mt_other', 'mt_multi_self', 'mt_multi_other', 'mt_frac_self', 'mt_frac_other', 'mt_cross', 'mt_frac_self_max', 'mt_frac_other_max', 'm200c', 'halo_mass', 'z_h', 'ra_true', 'dec_true', 'NMEM_true'] 21014
[[ 849.  887.  339.   82.    9.]
 [1702. 1807.  584.  121.    8.]
 [2525. 2645.  761.  128.    6.]
 [3437. 3923. 1007.  180.   14.]]
21014.0
0.5802789933506537 0.20034563541412354


In [36]:
import numpy as np
import pandas as pd
import GCRCatalogs
from crow import mass_proxy
from crow import ClusterAbundance
import pyarrow.parquet as pq
import pyarrow as pa
import matplotlib.pyplot as plt
from astropy.table import Table
# Imports
import time
import numpy as np
import matplotlib.pyplot as plt
import pyccl as ccl
from scipy.interpolate import interp1d

from crow import ClusterShearProfile
from crow import ClusterAbundance
from crow.recipes.binned_exact import ExactBinnedClusterRecipe
from crow.recipes.binned_grid import GridBinnedClusterRecipe
from crow import completeness_models, mass_proxy, purity_models, kernel
from crow.properties import ClusterProperty

# ---- Core cosmology and HMF (same numbers as your example) ----
hmf = ccl.halos.MassFuncDespali16(mass_def="200c")

cosmo = ccl.Cosmology(
    Omega_c=0.1109 / 0.71**2,
    Omega_b=0.02258 / 0.71**2,
    h=0.71,
    n_s=0.963,
    sigma8=0.8,
    w0=-1.0,
    wa=0.0,
    transfer_function="boltzmann_camb"
)



cl_abundandce = ClusterAbundance(cosmo, hmf)
m_pivot = 14.3
z_pivot = 0.5
z_bins = [(z_edges[i], z_edges[i+1]) for i in range(len(z_edges) -1)]
proxy_bins = [(richness_edges[i], richness_edges[i+1]) for i in range(len(richness_edges) - 1)]
redshift_distribution = kernel.SpectroscopicRedshift()
mass_richness = mass_proxy.MurataUnbinned(m_pivot, z_pivot)
print(z_bins, proxy_bins)
mass_richness.parameters["mu0"] = 3.6238
mass_richness.parameters["mu1"] = 0.2480
mass_richness.parameters["mu2"] = 0.0351

mass_richness.parameters["sigma0"] = 0.3591
mass_richness.parameters["sigma1"] = 0.0696
mass_richness.parameters["sigma2"] = -0.0226


print(z_edges, richness_edges)
# ---- Common grid / binning parameters for later cells ----
mass_grid_size = 80
redshift_grid_size = 40
proxy_grid_size = 40
sky_area = 440
mass_interval = (13., 16.0)


cl_abundandce = ClusterAbundance(cosmo, hmf)

recipe_grid_nocomp = GridBinnedClusterRecipe(
    mass_interval=mass_interval,
    cluster_theory=cl_abundandce,
    redshift_distribution=redshift_distribution,
    mass_distribution=mass_richness,
    proxy_grid_size=proxy_grid_size,
    redshift_grid_size=redshift_grid_size,
    mass_grid_size=mass_grid_size,
)
recipe_grid_nocomp.setup()


exact_t0 = time.time()
grid_nocomp_vals  = np.zeros((len(z_edges) -1,len(richness_edges) - 1))

for i, zb in enumerate(z_bins):
    for j, pb in enumerate(proxy_bins):
        grid_nocomp_vals[i,j]  = recipe_grid_nocomp.evaluate_theory_prediction_counts(np.array(zb), np.array(pb), sky_area)

[(np.float64(0.20034563541412354), np.float64(0.35025790333747864)), (np.float64(0.35025790333747864), np.float64(0.5001701712608337)), (np.float64(0.5001701712608337), np.float64(0.6500824391841888)), (np.float64(0.6500824391841888), np.float64(0.799994707107544))] [(np.float64(0.6989700198173523), np.float64(1.053681993484497)), (np.float64(1.053681993484497), np.float64(1.408393967151642)), (np.float64(1.408393967151642), np.float64(1.7631059408187868)), (np.float64(1.7631059408187868), np.float64(2.1178179144859315)), (np.float64(2.1178179144859315), np.float64(2.472529888153076))]
[0.20034564 0.3502579  0.50017017 0.65008244 0.79999471] [0.69897002 1.05368199 1.40839397 1.76310594 2.11781791 2.47252989]


In [35]:
print(grid_nocomp_vals)

[[1.47050813e+01 9.93777644e+03 2.76801102e+03 5.93394290e+01
  5.47669895e-01]
 [2.30822440e+01 1.90012511e+04 5.09042422e+03 9.31479026e+01
  6.98621764e-01]
 [2.74455076e+01 2.73196882e+04 6.99272023e+03 1.07347334e+02
  6.41595456e-01]
 [2.79457148e+01 3.33794261e+04 8.11871535e+03 1.03076006e+02
  4.83515150e-01]]
